"""AI Natural Language Explanation Layer powered by Gemini 1.5 Flash.

Core principle:
    AI explains facts computed deterministically.
    Never lets the LLM invent amounts; grounds all explanations strictly
    in the mathematical metadata generated by AnomalyDetector.
"""

from __future__ import annotations

import os
from typing import Optional
from src.schemas import AnomalyAlert


EXPLAINER_PROMPT = """You are an expert personal finance auditor.
Generate a concise, 1-2 sentence evidence-backed explanation for why this financial anomaly was flagged for the user.
Mention the specific numbers, dates, and baseline figures provided in the anomaly metadata.
Avoid jargon. Provide clear, actionable context (e.g. "Review your subscription settings", "Verify this new vendor").

Alert Type: {alert_type}
Merchant: {merchant}
Amount: {amount}
Metadata: {metadata}
Deterministic Explanation: {base_explanation}
"""


class AnomalyExplainer:
    """Generates natural language context for detected anomalies."""

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-1.5-flash") -> None:
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model_name = os.getenv("GEMINI_MODEL", model_name)
        self._client = None
        if self.api_key:
            try:
                from google import genai
                self._client = genai.Client(api_key=self.api_key)
            except Exception:
                self._client = None

    def is_available(self) -> bool:
        return self._client is not None

    def explain(self, alert: AnomalyAlert) -> str:
        """Generate or enhance anomaly explanation."""
        if not self.is_available():
            # Deterministic, grounded fallback
            return alert.explanation

        try:
            prompt = EXPLAINER_PROMPT.format(
                alert_type=alert.alert_type,
                merchant=alert.merchant,
                amount=alert.amount,
                metadata=alert.metadata,
                base_explanation=alert.explanation,
            )

            response = self._client.models.generate_content(
                model=self.model_name,
                contents=prompt,
            )

            if response and response.text:
                return response.text.strip()
            return alert.explanation
        except Exception:
            return alert.explanation
